title: Shin Tzehan
email: shintzehan@gmail.com
description: >- 
  Undergraduated in eecs, participate in electrical and computer engineering.
baseurl: "/" 
url: "https://www.shintzehan.com"
theme: minima
